/**
 * Declarations → CSS. The live preview and the exported stylesheet both come
 * through here, so what you see on the canvas is literally what ships.
 */

import type { Declaration, Mode, ResolvedTokens } from "../engine/types"

export function declarationBlock(declarations: Declaration[], selector: string): string {
    const body = declarations.map(([name, value]) => `    ${name}: ${value};`).join("\n")
    return `${selector} {\n${body}\n}`
}

/**
 * The preview scopes tokens to its own root instead of `:root`, so the brand
 * never leaks into the app's own chrome. Same declarations, different selector.
 */
export function previewCss(resolved: ResolvedTokens, rootSelector = "#preview-root"): string {
    return [
        declarationBlock(resolved.declarations.light, rootSelector),
        declarationBlock(resolved.declarations.dark, `${rootSelector}[data-theme="dark"]`),
    ].join("\n\n")
}

/**
 * Tailwind v4 exposes tokens as CSS variables under known namespaces, so an
 * `@theme inline` block that forwards our semantics turns them into utilities
 * (`bg-background`, `text-muted-foreground`, `rounded-md`) with no config file.
 */
function themeBlock(resolved: ResolvedTokens): string {
    const lines: string[] = []
    for (const token of resolved.semantics) {
        lines.push(`    --color-${token.name}: var(--${token.name});`)
    }
    for (const [name, value] of resolved.declarations.light) {
        if (
            name.startsWith("--radius-") ||
            name.startsWith("--space-") ||
            name.startsWith("--container-") ||
            name.startsWith("--shadow-") ||
            name.startsWith("--ease-") ||
            name.startsWith("--font-") ||
            name.startsWith("--text-")
        ) {
            lines.push(`    ${name}: var(${name});`)
        } else if (name.startsWith("--breakpoint-")) {
            // Literal, never `var()`. Tailwind builds its variants into
            // `@media` rules, and a custom property does not resolve there —
            // `@media (width >= var(--breakpoint-lg))` is invalid, so every
            // `lg:` utility silently stops applying. Verified against a real
            // Tailwind v4 build; this is the same trap the docs warn about.
            lines.push(`    ${name}: ${value};`)
        }
    }
    return `@theme inline {\n${lines.join("\n")}\n}`
}

export function toTokensCss(resolved: ResolvedTokens, options: { darkMedia?: boolean } = {}): string {
    const { meta } = resolved.config
    const header = [
        `/*`,
        ` * ${meta.name} — design tokens`,
        ` * Generated by Brand Forge. Do not edit by hand; edit the brand and re-export.`,
        ` *`,
        ` * Semantic tokens alias primitives, so a colour value appears exactly once per mode.`,
        ` * Use the semantic names. Reach for a primitive only when no semantic fits.`,
        ` */`,
    ].join("\n")

    const parts = [
        header,
        // `[data-theme="light"]` is spelled out rather than left to fall through
        // to `:root`. A toggle that writes "light" to get back from dark worked
        // only by accident before, and an accident is a thing that stops working.
        declarationBlock(resolved.declarations.light, ':root,\n[data-theme="light"]'),
        declarationBlock(resolved.declarations.dark, '[data-theme="dark"]'),
    ]

    // Off by default. Shipping a prefers-color-scheme block alongside the
    // attribute makes the docs' "dark mode is an attribute, not a media query"
    // a lie, and worse: on a dark-preference OS a toggle that only removes
    // `data-theme` can never get back to light. Opt in knowingly or not at all.
    if (options.darkMedia === true) {
        parts.push(
            `@media (prefers-color-scheme: dark) {\n${indent(
                declarationBlock(resolved.declarations.dark, ':root:not([data-theme="light"])'),
            )}\n}`,
        )
    }

    parts.push(themeBlock(resolved))
    return parts.join("\n\n") + "\n"
}

const indent = (block: string): string =>
    block
        .split("\n")
        .map((line) => `    ${line}`)
        .join("\n")

export const modeSelector = (mode: Mode): string =>
    mode === "light" ? ":root" : '[data-theme="dark"]'
