/**
 * DTCG JSON (W3C design-tokens format, 2025.10).
 *
 * This is an INTEROP artifact, not the source of truth — the typed BrandConfig
 * is. DTCG cannot express generative intent (seeds, chroma curves, the rules
 * that chose a foreground) without abusing `$extensions`, so those live in
 * `$extensions` purely as provenance for a possible future re-import.
 *
 * Modes: DTCG's theming module is still draft, so light and dark ship as two
 * top-level groups. That's a convention, and the file says so rather than
 * pretending otherwise.
 */

import { SCALE_ROLES, STEPS, type Mode, type ResolvedTokens } from "../engine/types"

const EXTENSION = "design.hendri.brandforge"

interface TokenNode {
    $type?: string
    $value?: unknown
    $description?: string
    $extensions?: Record<string, unknown>
    [key: string]: unknown
}

export function toDtcgJson(resolved: ResolvedTokens): string {
    const { config } = resolved

    const colorGroup = (mode: Mode): TokenNode => {
        const primitives: TokenNode = {
            $description: "Generated ramps. Tune colour here; do not reference these from code.",
        }
        for (const role of SCALE_ROLES) {
            const scale = resolved.scales[role]
            if (!scale) continue
            const steps: TokenNode = { $description: `${scale.name} — seeded from ${scale.seed}.` }
            for (const step of STEPS) {
                const swatch = scale.steps[mode][step]!
                steps[String(step)] = {
                    $value: {
                        colorSpace: "oklch",
                        components: [swatch.oklch.l, swatch.oklch.c, swatch.oklch.h],
                        hex: swatch.hex,
                    },
                    ...(swatch.overridden
                        ? { $extensions: { [EXTENSION]: { overridden: true } } }
                        : {}),
                }
            }
            primitives[role] = steps
        }

        const semantics: TokenNode = {
            $description: "The consumable layer. Everything here aliases a primitive.",
        }
        for (const token of resolved.semantics) {
            semantics[token.name] = {
                $value: `{color.${mode}.primitive.${token[mode].scale}.${token[mode].step}}`,
                $description: token.description,
            }
        }

        return { $type: "color", primitive: primitives, semantic: semantics }
    }

    const dimension = (value: number) => ({ $value: { value, unit: "px" } })

    const document: TokenNode = {
        $description: [
            `${config.meta.name} design tokens, generated by Brand Forge.`,
            "Light and dark are separate top-level groups under `color`: the DTCG theming module is",
            "still draft, so modes are a convention here rather than a spec feature.",
        ].join(" "),
        $extensions: {
            [EXTENSION]: {
                schemaVersion: config.$schemaVersion,
                brand: config.meta.slug,
                seeds: Object.fromEntries(config.color.scales.map((s) => [s.role, s.seed])),
            },
        },
        color: { light: colorGroup("light"), dark: colorGroup("dark") },
        space: {
            $type: "dimension",
            ...Object.fromEntries(
                config.spacing.blessed.map((px) => [String(px / config.spacing.basePx), dimension(px)]),
            ),
        },
        radius: {
            $type: "dimension",
            ...Object.fromEntries(
                Object.entries(resolved.radius).map(([step, px]) => [step, dimension(px)]),
            ),
        },
        type: {
            $type: "typography",
            ...Object.fromEntries(
                config.typography.roles.map((role) => [
                    role.role,
                    {
                        $value: {
                            fontFamily: config.typography.families[role.family],
                            fontSize: { value: role.sizeRem, unit: "rem" },
                            fontWeight: role.weight,
                            lineHeight: role.lineHeight,
                            ...(role.tracking ? { letterSpacing: role.tracking } : {}),
                        },
                    },
                ]),
            ),
        },
        duration: {
            $type: "duration",
            ...Object.fromEntries(
                Object.entries(config.motion.durations).map(([name, ms]) => [
                    name,
                    { $value: { value: ms, unit: "ms" } },
                ]),
            ),
        },
        easing: {
            $type: "cubicBezier",
            ...Object.fromEntries(
                Object.entries(config.motion.easings).map(([name, curve]) => [
                    name,
                    { $value: parseCubicBezier(curve), $description: curve },
                ]),
            ),
        },
    }

    return JSON.stringify(document, null, 2) + "\n"
}

/** DTCG wants the four control points, not the CSS function. */
function parseCubicBezier(curve: string): number[] {
    const match = curve.match(/cubic-bezier\(([^)]+)\)/)
    if (!match) return [0.4, 0, 0.2, 1]
    return match[1]!.split(",").map((part) => Number(part.trim()))
}
